### ISSUE TITLE
接受行情时使用P2S函数时，报AccessViolationException

### ISSUE THREAD

**Issue by wyh529211** [shawn666liu/FtdcNet.CTP#2]
作者您好，在订阅较多的合约时，调用OnTrnDepthMarketData时间时，使用P2S函数有可能程序会报出AccessViolationException错误。描述为: Attempted to read or write protected memory。请问有什么办法修复么？非常感谢

**Comment by shawn666liu** [comment]
需要确保不跨线程访问IntPtr，即OnRtnEventArgs.Param参数。
IntPtr传递到其他线程时，其内存可能已经被非托管代码释放。
所以必须在OnRtnEvent回调中，先用P2S得到ThostFtdcDepthMarketDataField，再将这个P2S的结果传递到其他线程。
